[package]
name = "todolist-hexa"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_derive = "1.0.219"
csv = "1.3.1"
rand = "0.8.5"
sqlite = "0.37"