name: test
on:
  push:
    branches:
      - main

jobs:
  rust-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Installer Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Lancer les tests
        run: |
          echo "Lancement des tests"
          cargo test